@echo off
rem ---------------------------------------------------------------------------
rem clean_generated.bat - remove every file generated by the LVGL Pro Editor.
rem Usage: double-click it, or run  clean_generated.bat  from cmd.
rem Note : this file is saved as UTF-8. The code page is switched to UTF-8 right
rem        below, so the Chinese messages further down display correctly.
rem        Keep the next few lines pure ASCII and free of "<" ">" "|" "&".
rem ---------------------------------------------------------------------------

rem remember the current code page, then switch to UTF-8
for /f "tokens=2 delims=:" %%c in ('chcp') do set "OLD_CP=%%c"
chcp 65001 >nul
setlocal

rem ===========================================================================
rem  删除内容（都是编辑器 Generate / 导出时会重新生成的东西）：
rem    项目级注册代码   根目录的 *_gen.c、*_gen.h
rem    界面代码         screens、components、widgets 下的 *_gen.c、*_gen.h
rem    烘焙字体数据     fonts 目录下的 *_data.c（cjk_*、icon_*、montserrat_*）
rem    烘焙图片数据     images 目录下的 *_data.c
rem    源文件列表       file_list_gen.cmake
rem    导出构建脚本     CMakeLists.txt（只删它，user_config.cmake 不动）
rem    预览运行时缓存   preview-bin 目录
rem    编辑器缓存       .cache.json
rem
rem  不删（这些是工程源或自己写的东西）：
rem    *.xml（project、globals、translations、screens）、H7_MediaPlayer_UI.c/.h、
rem    user_config.cmake、sim 目录、.vscode 目录、.gitignore、.mcp.json、
rem    字体与图片源文件（fonts 下的 .ttf、images 下的 .png）
rem
rem  清完后回编辑器点一次 Generate（或重新导出）即可恢复。
rem  所有路径都以本脚本所在目录为基准，不受当前工作目录影响。
rem ===========================================================================

set "ROOT=%~dp0"
set /a total=0

echo.
echo === 清理 LVGL Pro Editor 生成物 ===
echo 目录：%ROOT%
echo.

rem ---- 1) 根目录的项目级 gen 代码 ----
for /f "delims=" %%f in ('dir /b /a-d "%ROOT%*_gen.c" "%ROOT%*_gen.h" 2^>nul') do call :del "%ROOT%%%f"

rem ---- 2) 各界面目录下的 gen 代码（含子目录） ----
for %%d in (screens components widgets) do (
	if exist "%ROOT%%%d" for /f "delims=" %%f in ('dir /b /s /a-d "%ROOT%%%d\*_gen.c" "%ROOT%%%d\*_gen.h" 2^>nul') do call :del "%%f"
)

rem ---- 3) 烘焙的字体数据 / 图片数据 ----
for /f "delims=" %%f in ('dir /b /a-d "%ROOT%fonts\*_data.c" 2^>nul') do call :del "%ROOT%fonts\%%f"
for /f "delims=" %%f in ('dir /b /a-d "%ROOT%images\*_data.c" 2^>nul') do call :del "%ROOT%images\%%f"

rem ---- 4) 生成的源文件列表、导出的构建脚本、编辑器缓存 ----
for %%f in (file_list_gen.cmake CMakeLists.txt .cache.json) do call :del "%ROOT%%%f"

rem ---- 5) 本地预览运行时缓存（整个目录） ----
if exist "%ROOT%preview-bin\" (
	rd /s /q "%ROOT%preview-bin"
	echo   [目录] preview-bin\
	set /a total+=1
)

rem 想连构建产物一起清掉，把下面两行的 rem 去掉即可
rem if exist "%ROOT%preview-build\" ( rd /s /q "%ROOT%preview-build" ^& echo   [目录] preview-build\ ^& set /a total+=1 )
rem if exist "%ROOT%build\" ( rd /s /q "%ROOT%build" ^& echo   [目录] build\ ^& set /a total+=1 )

echo.
echo 完成：共删除 %total% 项。回编辑器点 Generate 可重新生成。
echo.
rem 结束后不暂停：双击运行时窗口自动关闭，终端里运行时只退出脚本
chcp %OLD_CP% >nul
exit /b

rem ---- 子过程：删一个文件并打印 ----
:del
if not "%~1"=="" if exist "%~1" (
	del /f /q "%~1" >nul
	echo   [文件] %~1
	set /a total+=1
)
exit /b
