/**
 * @file audio_res.h
 * @brief Audio 模块统一返回值桌面桩头文件, 与固件枚举保持一致
 */

#ifndef H7_SIM_STUB_AUDIO_RES_H
#define H7_SIM_STUB_AUDIO_RES_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef enum {
	AUDIO_RES_OK = 0,
	AUDIO_RES_EOF,
	AUDIO_RES_INVALID_ARG,
	AUDIO_RES_UNSUPPORTED_FORMAT,
	AUDIO_RES_UNSUPPORTED_SAMPLE_RATE,
	AUDIO_RES_NO_MEMORY,
	AUDIO_RES_BUFFER_TOO_SMALL,
	AUDIO_RES_FS_OPEN_FAILED,
	AUDIO_RES_FS_READ_FAILED,
	AUDIO_RES_FS_SEEK_FAILED,
	AUDIO_RES_FS_CLOSE_FAILED,
	AUDIO_RES_DECODER_OPEN_FAILED,
	AUDIO_RES_DECODE_FAILED,
	AUDIO_RES_DECODER_SEEK_FAILED,
	AUDIO_RES_METADATA_FAILED,
	AUDIO_RES_SAI_CONFIG_FAILED,
	AUDIO_RES_DMA_SIZE_INVALID,
	AUDIO_RES_DMA_START_FAILED,
	AUDIO_RES_DMA_CONTROL_FAILED,
	AUDIO_RES_DMA_TIMEOUT,
	AUDIO_RES_EMPTY_STREAM,
	AUDIO_RES_BUSY,
	AUDIO_RES_NOT_ACTIVE,
	AUDIO_RES_QUEUE_FULL,
	AUDIO_RES_TASK_CREATE_FAILED,
} audio_res_t;

const char * audio_res_str(audio_res_t res);


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* H7_SIM_STUB_AUDIO_RES_H */
